import { StyleSheet } from "react-native";

const B  = '#1A2F6E'; // dark blue
const R  = '#C01830'; // red
const W  = '#FFFFFF'; // white
const BG = '#F0F4FF'; // light blue tint for cards
const BORDER = '#D1D8F0';
const MUTED  = '#6B7280';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: W,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: BORDER,
    backgroundColor: W,
  },
  logoContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  logoBadge: {
    backgroundColor: R,
    padding: 8,
    borderRadius: 10,
    marginRight: 10,
  },
  logoText: {
    color: B,
    fontSize: 20,
    fontWeight: '900',
    letterSpacing: 0.5,
  },
  logoGreen: {
    color: R,
  },
  subtitle: {
    color: MUTED,
    fontSize: 9,
    fontWeight: '600',
    letterSpacing: 1,
    marginTop: -2,
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  iconButton: {
    marginRight: 16,
    position: 'relative',
  },
  notificationDot: {
    position: 'absolute',
    top: 2,
    right: 2,
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: R,
  },
  profileButton: {
    flexDirection: 'row',
    backgroundColor: BG,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 20,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: BORDER,
  },
  profileButtonText: {
    color: B,
    fontSize: 12,
    fontWeight: '700',
  },
  feedScroll: {
    flex: 1,
    padding: 16,
  },
  heroCard: {
    height: 380,
    marginBottom: 24,
  },
  heroImage: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(10, 14, 26, 0.55)',
    borderRadius: 24,
    padding: 20,
    justifyContent: 'flex-end',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
  },
  tagContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  topStoryTag: {
    backgroundColor: R,
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderRadius: 8,
    marginRight: 8,
  },
  topStoryTagText: {
    color: W,
    fontSize: 11,
    fontWeight: '800',
  },
  leagueTag: {
    color: '#CBD5E0',
    fontSize: 12,
    fontWeight: '700',
  },
  heroHeadline: {
    color: W,
    fontSize: 28,
    fontWeight: '900',
    fontStyle: 'italic',
    lineHeight: 34,
    marginBottom: 10,
  },
  heroTeaser: {
    color: '#CBD5E0',
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 16,
  },
  ctaContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  ctaText: {
    color: W,
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 1,
    marginRight: 4,
  },
  filterScroll: {
    flexDirection: 'row',
    marginBottom: 8,
  },
  // Region filter (inactive)
  filterTab: {
    marginRight: 8,
    paddingVertical: 7,
    paddingHorizontal: 14,
    borderRadius: 20,
    backgroundColor: W,
    borderWidth: 1.5,
    borderColor: BORDER,
  },
  // Liga active override applied inline in App.js
  activeFilterTab: {
    backgroundColor: B,
    borderColor: B,
  },
  filterTabText: {
    color: MUTED,
    fontSize: 13,
    fontWeight: '700',
  },
  activeFilterTabText: {
    color: W,
  },
  navBarWrapper: {
    position: 'absolute',
    bottom: 30,
    left: 0,
    right: 0,
    alignItems: 'center',
    paddingHorizontal: 16,
  },
  navBar: {
    flexDirection: 'row',
    backgroundColor: B,
    borderRadius: 30,
    paddingVertical: 10,
    paddingHorizontal: 12,
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    shadowColor: B,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.3,
    shadowRadius: 20,
    elevation: 10,
  },
  navTab: {
    padding: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  activeNavTab: {
    flexDirection: 'row',
    backgroundColor: R,
    borderRadius: 20,
    paddingVertical: 8,
    paddingHorizontal: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  activeNavTabText: {
    color: W,
    fontSize: 12,
    fontWeight: '800',
    marginLeft: 6,
  },
  placeholderContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: W,
  },
  placeholderText: {
    color: MUTED,
    fontSize: 18,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  adBanner: {
    backgroundColor: BG,
    borderWidth: 1,
    borderColor: BORDER,
    borderRadius: 12,
    paddingVertical: 8,
    paddingHorizontal: 16,
    width: '100%',
    marginBottom: 12,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 5,
    elevation: 3,
  },
  adBannerText: {
    color: MUTED,
    fontSize: 11,
    fontWeight: '600',
    letterSpacing: 0.3,
    textAlign: 'center',
  },
  adBannerLink: {
    color: R,
    fontWeight: '800',
  },
  burgerButton: {
    backgroundColor: BG,
    padding: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: BORDER,
    justifyContent: 'center',
    alignItems: 'center',
  },
  drawerOverlay: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    zIndex: 999,
    flexDirection: 'row',
  },
  drawerCloseDetector: {
    flex: 0.25,
    backgroundColor: 'rgba(0,0,0,0.4)',
  },
  drawerContainer: {
    flex: 0.75,
    backgroundColor: W,
    borderLeftWidth: 1,
    borderLeftColor: BORDER,
    paddingTop: 20,
  },
  drawerHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: BORDER,
  },
  drawerUserSection: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  drawerAvatar: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: B,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  drawerUserName: {
    color: B,
    fontSize: 14,
    fontWeight: '700',
  },
  drawerUserEmail: {
    color: MUTED,
    fontSize: 11,
  },
  drawerCloseButton: {
    padding: 4,
  },
  drawerMenuScroll: {
    flex: 1,
    paddingVertical: 12,
  },
  drawerItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 14,
    paddingHorizontal: 20,
    borderBottomWidth: 1,
    borderBottomColor: BG,
  },
  drawerItemIconWrapper: {
    width: 30,
    alignItems: 'center',
    marginRight: 14,
  },
  drawerItemText: {
    color: B,
    fontSize: 14,
    fontWeight: '600',
  },
  drawerItemSpecialText: {
    color: R,
    fontWeight: '700',
  },
  scoreCard: {
    backgroundColor: W,
    borderColor: BORDER,
    borderWidth: 1,
    borderRadius: 16,
    padding: 16,
    width: 240,
    marginRight: 14,
    shadowColor: B,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 5,
    elevation: 3,
  },
  scoreLeague: {
    color: MUTED,
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 0.8,
    marginBottom: 12,
  },
  scoreRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
  teamContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    marginRight: 8,
  },
  teamLogo: {
    width: 24,
    height: 24,
    borderRadius: 12,
    marginRight: 10,
    backgroundColor: BG,
  },
  teamName: {
    color: MUTED,
    fontSize: 15,
    fontWeight: '600',
    flex: 1,
  },
  teamScore: {
    color: MUTED,
    fontSize: 15,
    fontWeight: '600',
  },
  winnerTeam: {
    color: B,
    fontWeight: '800',
  },
  winnerScore: {
    color: R,
    fontWeight: '800',
    fontSize: 16,
  },
  gameStatus: {
    color: MUTED,
    fontSize: 9,
    fontWeight: '700',
    marginTop: 10,
    textAlign: 'right',
  },
  mediaCard: {
    backgroundColor: W,
    borderColor: BORDER,
    borderWidth: 1,
    borderRadius: 16,
    marginHorizontal: 16,
    marginBottom: 24,
    shadowColor: B,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 4,
  },
  drawerSignOutWrap: {
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderTopWidth: 1,
    borderTopColor: BORDER,
  },
  drawerSignOutBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: '#FFF0F2',
    borderRadius: 14,
    paddingVertical: 14,
    borderWidth: 1,
    borderColor: R,
  },
  drawerSignOutText: {
    color: R,
    fontSize: 15,
    fontWeight: '800',
  },
});

export default styles;
