import { StyleSheet } from 'react-native';
import type { ThemeColors } from './palettes';

export function createAppStyles(c: ThemeColors) {
  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: c.background,
    },
    header: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: 16,
      paddingVertical: 12,
      borderBottomWidth: 1,
      borderBottomColor: c.border,
      backgroundColor: c.surface,
    },
    logoContainer: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    logoBadge: {
      backgroundColor: c.accent,
      padding: 8,
      borderRadius: 10,
      marginRight: 10,
    },
    logoText: {
      color: c.text,
      fontSize: 20,
      fontWeight: '900',
      letterSpacing: 0.5,
    },
    logoGreen: {
      color: c.accent,
    },
    subtitle: {
      color: c.textMuted,
      fontSize: 9,
      fontWeight: '600',
      letterSpacing: 1,
      marginTop: -2,
    },
    headerActions: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    burgerButton: {
      backgroundColor: c.burgerBg,
      padding: 10,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: c.border,
      justifyContent: 'center',
      alignItems: 'center',
    },
    tickerReturnBanner: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: c.accent,
      paddingVertical: 10,
      paddingHorizontal: 14,
      gap: 10,
      borderBottomWidth: 1,
      borderBottomColor: 'rgba(255,255,255,0.2)',
    },
    tickerReturnBannerIcon: {
      width: 34,
      height: 34,
      borderRadius: 17,
      backgroundColor: 'rgba(255,255,255,0.2)',
      alignItems: 'center',
      justifyContent: 'center',
    },
    tickerReturnBannerTextWrap: {
      flex: 1,
    },
    tickerReturnBannerTitle: {
      color: '#FFFFFF',
      fontSize: 13,
      fontWeight: '800',
    },
    tickerReturnBannerSub: {
      color: 'rgba(255,255,255,0.85)',
      fontSize: 11,
      fontWeight: '600',
      marginTop: 1,
    },
    tickerReturnBannerClose: {
      padding: 4,
      marginLeft: 2,
    },
    navBarWrapper: {
      position: 'absolute',
      bottom: 30,
      left: 0,
      right: 0,
      alignItems: 'center',
      paddingHorizontal: 16,
      zIndex: 300,
      elevation: 30,
    },
    navBar: {
      flexDirection: 'row',
      backgroundColor: '#1A2F6E',
      borderRadius: 30,
      paddingVertical: 8,
      paddingHorizontal: 8,
      alignItems: 'center',
      width: '100%',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: 0.3,
      shadowRadius: 20,
      elevation: 10,
    },
    navTabItem: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 10,
      borderRadius: 20,
    },
    navTabItemActive: {
      backgroundColor: c.accent,
    },
    drawerOverlay: {
      position: 'absolute',
      top: 0,
      bottom: 0,
      left: 0,
      right: 0,
      zIndex: 999,
      flexDirection: 'row',
    },
    drawerCloseDetector: {
      flex: 0.25,
      backgroundColor: 'rgba(0,0,0,0.4)',
    },
    drawerContainer: {
      flex: 0.75,
      backgroundColor: c.surface,
      borderLeftWidth: 1,
      borderLeftColor: c.border,
      paddingTop: 20,
    },
    drawerHeader: {
      flexDirection: 'row',
      justifyContent: 'flex-end',
      alignItems: 'center',
      paddingHorizontal: 16,
      paddingBottom: 20,
      borderBottomWidth: 1,
      borderBottomColor: c.border,
    },
    drawerCloseButton: {
      padding: 4,
    },
    drawerMenuScroll: {
      flex: 1,
      paddingVertical: 12,
    },
    drawerItem: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 14,
      paddingHorizontal: 20,
      borderBottomWidth: 1,
      borderBottomColor: c.drawerItemBorder,
    },
    drawerItemIconWrapper: {
      width: 30,
      alignItems: 'center',
      marginRight: 14,
    },
    drawerItemText: {
      color: c.text,
      fontSize: 14,
      fontWeight: '600',
    },
    drawerSignOutWrap: {
      paddingHorizontal: 16,
      paddingVertical: 14,
      borderTopWidth: 1,
      borderTopColor: c.border,
    },
    drawerSignOutBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      backgroundColor: c.signOutBg,
      borderRadius: 14,
      paddingVertical: 14,
      borderWidth: 1,
      borderColor: c.accent,
    },
    drawerSignOutText: {
      color: c.accent,
      fontSize: 15,
      fontWeight: '800',
    },
  });
}
