import { StyleSheet } from 'react-native';

export function getPostCategoryStyles(c) {
  const isDark = c.mode === 'dark';
  return {
    News: { bg: c.chipBg, color: c.text },
    Spielbericht: { bg: isDark ? '#2A1520' : '#FFF0F2', color: c.accent },
    'Trainings-Update': { bg: isDark ? '#0F2A22' : '#ECFDF5', color: '#059669' },
    Event: { bg: isDark ? '#2A220F' : '#FFFBEB', color: '#D97706' },
  };
}

export function createPostCardStyles(c) {
  return StyleSheet.create({
    postWrapper: {
      marginBottom: 12,
    },
    card: {
      backgroundColor: c.surface,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: c.border,
      padding: 16,
      marginBottom: 0,
    },
    cardWithActions: {
      borderBottomLeftRadius: 0,
      borderBottomRightRadius: 0,
      borderBottomWidth: 0,
    },
    actionsRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: c.surface,
      borderWidth: 1,
      borderColor: c.border,
      borderTopWidth: 1,
      borderBottomLeftRadius: 16,
      borderBottomRightRadius: 16,
      paddingHorizontal: 8,
      paddingVertical: 10,
    },
    actionBtn: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 5,
      paddingVertical: 4,
    },
    actionText: {
      color: c.textMuted,
      fontSize: 11,
      fontWeight: '700',
    },
    actionTextActive: {
      color: c.accent,
    },
    teamHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      marginBottom: 12,
      paddingBottom: 12,
      borderBottomWidth: 1,
      borderBottomColor: c.border,
    },
    teamAvatar: {
      width: 40,
      height: 40,
      borderRadius: 10,
    },
    teamAvatarPlaceholder: {
      width: 40,
      height: 40,
      borderRadius: 10,
      backgroundColor: c.mode === 'dark' ? '#3B5080' : '#1A2F6E',
      alignItems: 'center',
      justifyContent: 'center',
    },
    teamAvatarText: { color: '#FFFFFF', fontSize: 16, fontWeight: '900' },
    teamHeaderText: { flex: 1 },
    teamName: { color: c.text, fontSize: 14, fontWeight: '800' },
    teamMeta: { color: c.textMuted, fontSize: 11, marginTop: 2 },
    cardTop: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 8,
      gap: 8,
    },
    cardTopRight: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    editBtn: {
      width: 28,
      height: 28,
      borderRadius: 8,
      backgroundColor: c.card,
      borderWidth: 1,
      borderColor: c.border,
      alignItems: 'center',
      justifyContent: 'center',
    },
    categoryBadge: {
      borderRadius: 8,
      paddingHorizontal: 8,
      paddingVertical: 4,
    },
    categoryText: { fontSize: 10, fontWeight: '800', letterSpacing: 0.5 },
    dateText: { color: c.textMuted, fontSize: 11, fontWeight: '600' },
    title: {
      color: c.text,
      fontSize: 17,
      fontWeight: '900',
      letterSpacing: 0.2,
      marginBottom: 6,
    },
    content: {
      color: c.textMuted,
      fontSize: 13,
      lineHeight: 19,
      fontWeight: '500',
    },
    postImage: {
      width: '100%',
      height: 160,
      borderRadius: 12,
      marginTop: 12,
      backgroundColor: c.card,
    },
  });
}

export function createPostCreateStyles(c) {
  return StyleSheet.create({
    safe: { flex: 1, backgroundColor: c.background },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 16,
      paddingVertical: 12,
      borderBottomWidth: 1,
      borderBottomColor: c.border,
    },
    backBtn: { flexDirection: 'row', alignItems: 'center', gap: 6, width: 72 },
    backBtnText: { color: c.text, fontSize: 14, fontWeight: '700' },
    headerTitle: { color: c.text, fontSize: 16, fontWeight: '900' },
    successToast: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      backgroundColor: '#059669',
      marginHorizontal: 16,
      marginTop: 12,
      borderRadius: 12,
      paddingHorizontal: 14,
      paddingVertical: 12,
    },
    successToastText: { color: '#FFFFFF', fontSize: 13, fontWeight: '700', flex: 1 },
    scroll: { padding: 20, paddingBottom: 40 },
    fieldWrap: { marginBottom: 16 },
    fieldLabel: { color: c.text, fontSize: 10, fontWeight: '800', letterSpacing: 0.8, marginBottom: 8 },
    input: {
      backgroundColor: c.card,
      borderRadius: 12,
      borderWidth: 1.5,
      borderColor: c.border,
      paddingHorizontal: 14,
      paddingVertical: 12,
      color: c.text,
      fontSize: 15,
      fontWeight: '600',
    },
    inputMulti: { minHeight: 160, paddingTop: 12 },
    selectTrigger: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: c.card,
      borderRadius: 12,
      borderWidth: 1.5,
      borderColor: c.border,
      paddingHorizontal: 14,
      paddingVertical: 14,
    },
    selectText: { color: c.text, fontSize: 15, fontWeight: '600' },
    imagePickerBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      backgroundColor: c.card,
      borderRadius: 12,
      borderWidth: 1.5,
      borderColor: c.border,
      borderStyle: 'dashed',
      paddingVertical: 28,
    },
    imagePickerText: { color: c.text, fontSize: 14, fontWeight: '700' },
    imagePreviewWrap: { position: 'relative' },
    imagePreview: {
      width: '100%',
      height: 180,
      borderRadius: 12,
      backgroundColor: c.card,
    },
    removeImageBtn: {
      position: 'absolute',
      top: 8,
      right: 8,
      width: 28,
      height: 28,
      borderRadius: 14,
      backgroundColor: 'rgba(0,0,0,0.55)',
      alignItems: 'center',
      justifyContent: 'center',
    },
    submitBtn: {
      backgroundColor: c.accent,
      borderRadius: 14,
      paddingVertical: 16,
      alignItems: 'center',
      justifyContent: 'center',
      minHeight: 52,
      marginTop: 8,
    },
    submitBtnDisabled: { opacity: 0.7 },
    submitBtnText: { color: '#FFFFFF', fontSize: 16, fontWeight: '900' },
    modalBackdrop: {
      flex: 1,
      backgroundColor: c.mode === 'dark' ? 'rgba(0,0,0,0.6)' : 'rgba(26,47,110,0.4)',
      justifyContent: 'flex-end',
    },
    modalSheet: {
      backgroundColor: c.surface,
      borderTopLeftRadius: 20,
      borderTopRightRadius: 20,
      paddingBottom: 28,
    },
    modalTitle: {
      color: c.text,
      fontSize: 16,
      fontWeight: '900',
      paddingHorizontal: 20,
      paddingVertical: 16,
      borderBottomWidth: 1,
      borderBottomColor: c.border,
    },
    modalItem: {
      paddingHorizontal: 20,
      paddingVertical: 16,
      borderBottomWidth: 1,
      borderBottomColor: c.border,
    },
    modalItemActive: { backgroundColor: c.card },
    modalItemText: { color: c.text, fontSize: 15, fontWeight: '600' },
    modalItemTextActive: { fontWeight: '900' },
  });
}
