import { StyleSheet } from 'react-native';

export function createTeamSponsorsStyles(c) {
  const isDark = c.mode === 'dark';
  const brandBlue = isDark ? '#3B5080' : c.primary;

  return StyleSheet.create({
    safe: { flex: 1, backgroundColor: c.background },
    scroll: { paddingHorizontal: 20, paddingBottom: 40 },
    backBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      paddingHorizontal: 20,
      paddingVertical: 14,
    },
    backBtnText: { color: c.text, fontSize: 14, fontWeight: '700' },
    title: {
      color: c.text,
      fontSize: 24,
      fontWeight: '900',
      marginBottom: 6,
    },
    subtitle: {
      color: c.textMuted,
      fontSize: 14,
      lineHeight: 20,
      marginBottom: 20,
    },
    sectionLabel: {
      color: c.textMuted,
      fontSize: 10,
      fontWeight: '800',
      letterSpacing: 1.2,
      marginBottom: 10,
      marginTop: 8,
    },
    card: {
      backgroundColor: c.card,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: c.border,
      padding: 16,
      marginBottom: 14,
    },
    sponsorRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
    },
    sponsorLogo: {
      width: 52,
      height: 52,
      borderRadius: 12,
      backgroundColor: c.surface,
    },
    sponsorLogoPlaceholder: {
      width: 52,
      height: 52,
      borderRadius: 12,
      backgroundColor: c.surface,
      borderWidth: 1,
      borderColor: c.border,
      alignItems: 'center',
      justifyContent: 'center',
    },
    sponsorLogoInitial: {
      color: c.text,
      fontSize: 16,
      fontWeight: '900',
    },
    sponsorInfo: { flex: 1 },
    sponsorName: {
      color: c.text,
      fontSize: 15,
      fontWeight: '800',
      marginBottom: 2,
    },
    sponsorUrl: {
      color: c.textMuted,
      fontSize: 12,
      fontWeight: '500',
    },
    rowActions: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    iconBtn: {
      width: 36,
      height: 36,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: c.border,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: c.surface,
    },
    emptyWrap: {
      alignItems: 'center',
      paddingVertical: 28,
      gap: 8,
    },
    emptyText: {
      color: c.textMuted,
      fontSize: 14,
      textAlign: 'center',
      lineHeight: 20,
    },
    formCard: {
      backgroundColor: c.card,
      borderRadius: 16,
      borderWidth: 1.5,
      borderColor: brandBlue,
      padding: 16,
      marginBottom: 18,
    },
    formTitle: {
      color: c.text,
      fontSize: 16,
      fontWeight: '800',
      marginBottom: 14,
    },
    fieldLabel: {
      color: c.textMuted,
      fontSize: 10,
      fontWeight: '800',
      letterSpacing: 0.8,
      marginBottom: 8,
      marginTop: 4,
    },
    input: {
      backgroundColor: c.surface,
      borderWidth: 1.5,
      borderColor: c.border,
      borderRadius: 12,
      paddingHorizontal: 14,
      paddingVertical: 12,
      color: c.text,
      fontSize: 15,
      fontWeight: '500',
      marginBottom: 12,
    },
    logoPicker: {
      alignSelf: 'flex-start',
      marginBottom: 12,
    },
    logoPreview: {
      width: 88,
      height: 88,
      borderRadius: 16,
      backgroundColor: c.surface,
      borderWidth: 1,
      borderColor: c.border,
    },
    logoPreviewPlaceholder: {
      width: 88,
      height: 88,
      borderRadius: 16,
      backgroundColor: c.surface,
      borderWidth: 1,
      borderColor: c.border,
      alignItems: 'center',
      justifyContent: 'center',
    },
    logoHint: {
      color: c.textMuted,
      fontSize: 11,
      fontWeight: '600',
      marginTop: 6,
    },
    formActions: {
      flexDirection: 'row',
      gap: 10,
      marginTop: 4,
    },
    saveBtn: {
      flex: 1,
      backgroundColor: brandBlue,
      borderRadius: 12,
      paddingVertical: 14,
      alignItems: 'center',
    },
    saveBtnText: {
      color: '#FFFFFF',
      fontSize: 14,
      fontWeight: '800',
    },
    cancelBtn: {
      flex: 1,
      backgroundColor: c.surface,
      borderRadius: 12,
      paddingVertical: 14,
      alignItems: 'center',
      borderWidth: 1,
      borderColor: c.border,
    },
    cancelBtnText: {
      color: c.text,
      fontSize: 14,
      fontWeight: '700',
    },
    addBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      backgroundColor: c.card,
      borderRadius: 14,
      borderWidth: 1.5,
      borderColor: c.border,
      borderStyle: 'dashed',
      paddingVertical: 16,
      marginTop: 4,
    },
    addBtnText: {
      color: c.text,
      fontSize: 14,
      fontWeight: '800',
    },
    disabled: { opacity: 0.65 },
  });
}
